# curl RPC_URL -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
#POST https://main-light.eth.linkpool.io
POST http://3.110.153.211:8545
Content-Type: application/json

{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x10f2684903be65c453a14b47676bac6138822c67aa27d56d9bd765bca8a9a02b"],"id":1}

###

# curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' http://127.0.0.1:8546
POST http://3.110.153.211:8545
Content-Type: application/json

{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}

###

### Send POST request with json body
POST http://localhost:10771/api/v1/thegraph/deploy
Content-Type: application/json

{"nodeEthereumUrl":"mainnet:https://eth-mainnet.alchemyapi.io/v2/wHl5-FZKD68DlhCuUiOXgYh4Z0q0L5fh ","ethereumUrl":"https://rinkeby.infura.io/v3/af7a79eb36f64e609b5dda130cd62946","ethereumNetwork":"rinkeby","indexerAddress":"0x9438BbE4E7AF1ec6b13f75ECd1f53391506A12DF","mnemonic":"please output text solve glare exit divert boil nerve eagle attack turkey"}


### POST
POST http://59.80.40.149:38888/api/v1/config/settting
Content-Type: application/json

{"chainApi":"ws://183.66.65.207:49944","seedOrPhrase":"tomato denial broccoli video correct spring link oval ostrich category stereo beauty","publicIp":"59.80.40.149","publicPort":34001}

###
# # curl https://main-light.eth.linkpool.io -H 'Content-Type: application/json' -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x01aae536f2af204cf49bce218cc4fcb668037866124c80316ea4dbd234991292"],"id":1}'

###
GET http://localhost:34003/api/v1/chains/pullImage
