version: "3.2"

services:
  docker:
    container_name: docker
    image: "docker:dind"
    privileged: true
    network_mode: host
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - "docker-certs:/certs/client"

  provider:
    container_name: hamster-provider
    image: "hamstershare/hamster-provider:v1.3.0"
    restart: always
    privileged: true
    network_mode: host
    environment:
      DOCKER_HOST: "tcp://127.0.0.1:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
      LISTEN_ADDR: "0.0.0.0"
    volumes:
      - "config:/root/.hamster-provider"
      - "docker-certs:/certs/client:ro"
    depends_on:
      - docker
volumes:
  config:
  docker-certs:
