version: "3.2"

services:

  provider:
    container_name: hamster-provider
    image: "hamstershare/hamster-provider:v1.3.0"
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - "config:/root/.hamster-provider"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  config:
