version: "3.9"
services:
  nearcore:
    image: nearup/nearprotocol
    container_name: nearcore
    volumes:
      - near-data-volume:/root/.near
    ports:
      - "3030:3030"
    command: ["run", "{{ .Network }}"]
volumes:
  near-data-volume:

#    Network:
#    shardnet|guildnet|testnet|betanet|mainnet|localnet
