version: "3.9"
services:
  fullnode:
    container_name: sui-fullnode
    image: mysten/sui-node:stable
    ports:
      - "9000:9000"
      - "9184:9184"
    expose:
      - "9000"
      - "9184"
    volumes:
      - ./sui/fullnode-template.yaml:/sui/fullnode.yaml:ro
      - ./sui/genesis.blob:/sui/genesis.blob:ro
      - sui-data-volume:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  sui-data-volume:
