global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dtl'
    static_configs:
    - targets: ['dtl:7878']

  - job_name: 'healthcheck'
    static_configs:
    - targets: ['healthcheck:7300']

  - job_name: 'fault-detector'
    static_configs:
    - targets: ['fault-detector:7300']
