version: "3"
services:
  ethereum:
    image: ethereum/client-go
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - "ethereum-data:/root"
    command:
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--{{ .Network }}"
volumes:
  ethereum-data: {}
